spring:
  datasource:
    url: jdbc:mysql://localhost:3306/book_manager
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver

  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
server:
  port: 8080
logging:
  level:
    sql: debug
    org.hibernate.type: trace